blank_issues_enabled: false
contact_links:
  - name: ğŸ§© Feature Request
    url: https://github.com/IRINFOSYS-LIMITED/.github/issues/new?template=feature_request.yml
    about: Suggest new features or enhancements.
  - name: ğŸ Bug Report
    url: https://github.com/IRINFOSYS-LIMITED/.github/issues/new?template=bug_report.yml
    about: Report a problem or unexpected behavior.
  - name: âœ… Task
    url: https://github.com/IRINFOSYS-LIMITED/.github/issues/new?template=task.yml
    about: Create a new task or subtask for the sprint.
